### ISSUE TITLE
omp_set_nested routine deprecated

### ISSUE THREAD

**Issue by rosella1234** [samuelstjean/nlsam#100]
When running nlsam on CentOS server, 
`nlsam_denoising data.nii.gz denoised.nii.gz auto bvals bvecs 3 -m mask.nii.gz --noise_est auto --cores 15 -v`
during performing of stabilization the following warning starts iteratively appear in loop 
`OMP: Info #274: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.`
How can this be solved? Is it just a warning? Can I let the code go despite this message appearing in loop?
My OS features are:
lsb_release -a
LSB Version: :core-4.1-amd64:core-4.1-noarch
Distributor ID: CentOS
Description: CentOS Linux release 7.8.2003 (Core)
Release: 7.8.2003
Codename: Core
thank you
Rosella

**Comment by samuelstjean** [comment]
Seems like it's just a warning, it will probably be fixed internally whenever openblas is updated I'd guess.

**Comment by rosella1234** [comment]
So should I keep it go ? 
thanks

**Comment by samuelstjean** [comment]
it's probably fine, you might want to squelch them it if spams the terminal too much

**Comment by rosella1234** [comment]
I sent the process on back ground, so it is not a problem

**Comment by samuelstjean** [comment]
Normally that should be fixed, as it was something originating from spams downstream I think.
