### ISSUE TITLE
applying the bias correction framework to other denoising methods

### ISSUE THREAD

**Issue by plzcallmewdd** [samuelstjean/nlsam#138]
hi, how can I utilize this bias correction framework with other denoising methods? I’ve noticed that simply denoising the transformed results can lead to negative values

thank you:)

**Comment by samuelstjean** [comment]
Add the option **--no_denoising** and **--save_stab** _filename_, this should perform only the bias correction and skip the whole denoising part. There's couple other option also to use you can check with **--help**

**Comment by plzcallmewdd** [comment]
I tried to use patch2self (another denoising method) to denoise the corrected data, but I found that the result obtained had negative values (e.g. -1700), which would cause errors in calculating PSNR.  

:(
Could you please help me understand why this might be happening?

**Comment by plzcallmewdd** [comment]
thanks for the quick reply

I tried to use patch2self (another denoising method) to denoise the corrected data, but I found that the result obtained had negative values (e.g. -1700), which would cause errors in calculating PSNR.

:(
Could you please help me understand why this might be happening?

**Comment by plzcallmewdd** [comment]
thanks for the reply！

I tried to use patch2self (another denoising method) to denoise the corrected data, but I found that the result obtained had negative values (e.g. -1700), which would cause errors in calculating PSNR. Is this result normal? Perhaps I need to do some additional processing on the denoising results?

:(

**Comment by samuelstjean** [comment]
Well patch2self is pretty much just linear regression one volume at a time, so it probably has no way to deal with negative prediction. Try this one or mppca from mrtrix perhaps, they should be more robust.

**Comment by plzcallmewdd** [comment]
thanks!
