### ISSUE TITLE
Add verbose option to nlsam

### ISSUE THREAD

**Issue by mdesco** [samuelstjean/nlsam#2]
If possible, can you "quiet" nlsam by default and/or add a verbose option.

**Comment by samuelstjean** [comment]
I mostly removed everything in the end, except two lines saying how much time it takes by iteration and the progress, so it's easy to estimate the total runtime, 

The rest was mostly for debugging purpose for myself, so I just commented everything.

**Comment by samuelstjean** [comment]
I went the other way around and pretty much stripped the debug stuff as it was only useful to myself.
Now it display a small progress report instead along the way, so it kind of quiets stuff forever.
