### ISSUE TITLE
got multiple values for argument 'n_cores'

### ISSUE THREAD

**Issue by marcelzwiers** [samuelstjean/nlsam#52]
Sorry, never mind

**Comment by samuelstjean** [comment]
I recently changed stuff in the internal functions and multiprocessing, did
you re-run cython + install step or this is on a new install? Pulling the
files unfortunately does not automatically rebuilds the c parts of the
code, but a python setup.py build_ext -i (or relevant install line) should
do it.

**Comment by marcelzwiers** [comment]
Solved

**Comment by marcelzwiers** [comment]
I indeed solved it by reinstalling nlsam (after the pull).

2017-07-12 15:32 GMT+02:00 Samuel St-Jean <notifications@github.com>:

> I recently changed stuff in the internal functions and multiprocessing, did
> you re-run cython + install step or this is on a new install? Pulling the
> files unfortunately does not automatically rebuilds the c parts of the
> code, but a python setup.py build_ext -i (or relevant install line) should
> do it.
>

**Comment by samuelstjean** [comment]
Good if everyone seems to be in working order then, I'll close the issue.
