### ISSUE TITLE
how to use nlsam denoising 

### ISSUE THREAD

**Issue by rosella1234** [samuelstjean/nlsam#85]
I used autodmri to estimate N and sigma from my noisy data , as a result I have sigma.nii.gz and N.nii.gz images. How do I use them in order to denoise my dataset given the noise distribution previously estimated? thank you,
Rosella

**Comment by samuelstjean** [comment]
You can pass them to the version in master from the command line directly using the name of the output files. It is also possible now to directly estimate them internally by passing --noise_est auto, the help should detail the specifics if you need more info.

**Comment by rosella1234** [comment]
Thank you I saw that auto option. As well as SNR calculation, is that right
to do: image denoised with nlsam/std noise that is the sigma.nii.gz
obtained with autodmri?
Thank you
Rosella

Il dom 12 gen 2020, 15:56 Samuel St-Jean <notifications@github.com> ha
scritto:

**Comment by samuelstjean** [comment]
I'd guess, I'm not sure what you mean, but yes a rough snr calculation would always be signal / noise_std in the usual sense we define it I'd say.

**Comment by rosella1234** [comment]
Yes I just wanted to know if sigma. Nii. Gz obtained from autodmri is ok as
noise sts.
Thanks
Rosella

Il dom 12 gen 2020, 19:24 Samuel St-Jean <notifications@github.com> ha
scritto:

**Comment by rosella1234** [comment]
*noise std.
