### ISSUE TITLE
nlsam version

### ISSUE THREAD

**Issue by rosella1234** [samuelstjean/nlsam#93]
Hi I have just download and installed 6.0.1 nlsam version but the option "auto" for N does not work. I would like to know which version has this feature.
Thanks 
Rosella

**Comment by samuelstjean** [comment]
you would currently need to use the master branch (from source) for that, I didn't have time yet to put it together in an official version.

**Comment by rosella1234** [comment]
ok thank you. I managed to figure it out. I now have another issue since after launching nlsam_denoising script it says:

rosella@vivi:/media/rosella/TOSHIBA EXT/dkeTest/100610/Diffusion_3T$ nlsam_denoi                          sing data.nii.gz denoised_preproc.nii.gz auto bvals bvecs 5 -m mask.nii.gz --b0_                          threshold 100 --noise_est auto --verbose --force &
[1] 26064
rosella@vivi:/media/rosella/TOSHIBA EXT/dkeTest/100610/Diffusion_3T$ 2020-04-16                           10:44 - nlsam - INFO - Verbosity is on
2020-04-16 10:45 - nlsam - INFO - Loading data /media/rosella/TOSHIBA EXT/dkeTes                          t/100610/Diffusion_3T/data.nii.gz
2020-04-16 10:45 - nlsam - INFO - Loading mask /media/rosella/TOSHIBA EXT/dkeTes                          t/100610/Diffusion_3T/mask.nii.gz
2020-04-16 10:45 - nlsam - INFO - Estimating noise with method auto
[Parallel(n_jobs=8)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=8)]: Done  34 tasks      | elapsed:   46.3s
[Parallel(n_jobs=8)]: Done 145 out of 145 | elapsed:  4.3min finished
2020-04-16 10:50 - nlsam - INFO - Now performing stabilization
[Parallel(n_jobs=8)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=8)]: Done  34 tasks      | elapsed:  1.1min
Traceback (most recent call last):
  File "/usr/local/bin/nlsam_denoising", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/rosella/nlsam/scripts/nlsam_denoising", line 507, in <module>
    main()
  File "/home/rosella/nlsam/scripts/nlsam_denoising", line 456, in main
    n_cores=n_cores)
  File "/home/rosella/nlsam/nlsam/bias_correction.py", line 59, in stabilization
    verbose=verbose)(delayed(multiprocess_stabilization)(*args) for args in argl                          ist)
  File "/usr/local/lib/python2.7/dist-packages/joblib/parallel.py", line 1017, i                          n __call__
    self.retrieve()
  File "/usr/local/lib/python2.7/dist-packages/joblib/parallel.py", line 909, in                           retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/usr/local/lib/python2.7/dist-packages/joblib/_parallel_backends.py", li                          ne 562, in wrap_future_result
    return future.result(timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/joblib/externals/loky/_base.py",                           line 426, in result
    return self.__get_result()
  File "/usr/local/lib/python2.7/dist-packages/joblib/externals/loky/_base.py",                           line 381, in __get_result
    raise self._exception
pickle.PicklingError: Could not pickle the task to send it to the workers.

This was caused directly by
"""
IOError: [Errno 28] No space left on device
"""
What the problem could be ?

**Comment by samuelstjean** [comment]
Well it says no space left on device and it looks like you are running it locally on an external drive, I'd guess it truly ran out of space (such as in the temp folder /tmp ) while dispatching stuff or it didn't have write access. You can also just point it to a regular location maybe as a workaround, might be slower a little bit though. 
A quick explanation from https://joblib.readthedocs.io/en/latest/parallel.html#parallel is roughly 

Folder to be used by the pool for memmapping large arrays for sharing memory with worker processes. If None, this will try in order:

+    a folder pointed by the **JOBLIB_TEMP_FOLDER** environment variable,
  +  /dev/shm if the folder exists and is writable: this is a RAM disk filesystem available by default on modern Linux distributions,
   + the default system temporary folder that can be overridden with TMP, TMPDIR or TEMP environment variables, typically /tmp under Unix operating systems.

If your temp folder is not on ram (which it may run out of and explain what is happening here), you could try prepending to the command **JOBLIB_TEMP_FOLDER=/tmp** and see if it runs.

**Comment by rosella1234** [comment]
Thank you for your response. While I try to solve it,
I will attach  the output of the "df -h" command , which could help:
df -h
Filesystem      Size  Used Avail Use% Mounted on
udev             10M   10M   12K 100% /dev
tmpfs           6.3G   66M  6.3G   2% /run
/dev/sda1       129G   94G   28G  78% /
tmpfs            16G   92K   16G   1% /dev/shm
tmpfs           5.0M  4.0K  5.0M   1% /run/lock
tmpfs            16G     0   16G   0% /sys/fs/cgroup
/dev/sda6       1.7T  663G  904G  43% /home
tmpfs           3.2G   16K  3.2G   1% /run/user/1004
/dev/sdb2       3.7T  1.5T  2.2T  41% /media/rosella/TOSHIBA EXT
/dev/sdc1       1.9T  673G  1.2T  37% /media/rosella/BiolabHD
tmpfs           3.2G     0  3.2G   0% /run/user/1002
 By the way, I have tried to launch  the nlsam script both on external hard disk both on my linux PC and it gives the same aforementioned error.

**Comment by samuelstjean** [comment]
Seems like there is plenty of space though, maybe there is no write permission in /dev/shm? I'm not exactly sure since I never experienced the problem myself actually.

**Comment by rosella1234** [comment]
The strange thing is that a couple of months ago I launched the same script on the same PC and everything went ok .

**Comment by rosella1234** [comment]
Should I put this command _JOBLIB_TEMP_FOLDER=/tmp before nlsam_denoising?

**Comment by samuelstjean** [comment]
Could be worth a try (without the first underscore I think), if it was an issue with the permissions of /dev/shm, I'm really not sure what is happening honestly. It should redirect writing to /tmp normally (or any other folder of your choice you can write to).

**Comment by rosella1234** [comment]
I think /dev/shm is available and not full, the proble seems /dev that is udev filesystem. Me neither have no idea on how to solve the issue without damaging !

**Comment by rosella1234** [comment]
Could install and use nlsam via docker  be a solution in your opinion?
thanks ,
Rosella

**Comment by rosella1234** [comment]
Sorry but where JOBLIB_TEMP_FOLDER environment variable is?
I can't find it in nlsam_denosing script .
thanks

**Comment by samuelstjean** [comment]
It could be an idea to try it on docker indeed, as for the variable you can just set it into your shell as for example **export JOBLIB_TEMP_FOLDER=/tmp && rest of the stuff**, it needs to be redone each time you call a new shell though.

**Comment by rosella1234** [comment]
With exportit doesn't work and the strange thing is that trying on 2 different laptops gives the same errror. 
I will try using  docker

**Comment by rosella1234** [comment]
Also because the output of df -h is now:
udev             10M     0   10M   0% /dev
tmpfs           6.3G   66M  6.3G   2% /run
/dev/sda1       129G   94G   28G  78% /
tmpfs            16G   92K   16G   1% /dev/shm
tmpfs           5.0M  4.0K  5.0M   1% /run/lock
tmpfs            16G     0   16G   0% /sys/fs/cgroup
/dev/sda6       1.7T  663G  904G  43% /home
tmpfs           3.2G   16K  3.2G   1% /run/user/1004
/dev/sdb2       3.7T  1.5T  2.2T  41% /media/rosella/TOSHIBA EXT
/dev/sdc1       1.9T  673G  1.2T  37% /media/rosella/BiolabHD
tmpfs           3.2G     0  3.2G   0% /run/user/1002

**Comment by rosella1234** [comment]
One more thing, what is the average time for processing a subject with nlsam?
Is it possible it takes 40 hours per subject? Is there a way to set options in order to fasten it? I have got a set of 30 subjects so it would take to long.
Thanks 
Rosella

**Comment by samuelstjean** [comment]
That seems indeed overly long, it takes about 15 mins on my computer for a regular 2 mm iso dataset and about the same on our computing cluster for an hcp dataset. Of course that depends on your computer, but using a brain mask for example makes less voxels to process and it's faster as a result.

Other than that, if you have a 'newer' processor, old libs tends to be not optimized for them, you could try the conda_mkl docker file to see if it's faster, I think it was about 2x faster on my university desktop. You'll need to edit one line ot make it fetch master though, but it should be straightforward.

**Comment by rosella1234** [comment]
I am working with HCP  data and using a mask for each subject. I used auto options both for N and sigma then thought of using 1 for N in order to fasten computation.
that is the average time for iteration it takes on denoising one example subject:
`rosella@vivi:~/nlsam_denoising$ export JOBLIB_TEMP_FOLDER=/tmp && nlsam_denoising data.nii.gz dki_nlsam.nii.gz 1 bvals bvecs 5 -m mask.nii.gz --b0_threshold 100 --noise_est local_std --fix_implausible  --verbose
2020-04-17 10:55 - nlsam - INFO - Verbosity is on
2020-04-17 10:55 - nlsam - WARNING - Option --implausible_signal_fix has been deprecated
2020-04-17 10:56 - nlsam - INFO - Loading data /home/rosella/nlsam_denoising/data.nii.gz
2020-04-17 10:56 - nlsam - INFO - Loading mask /home/rosella/nlsam_denoising/mask.nii.gz
2020-04-17 10:56 - nlsam - INFO - Estimating noise with method local_std
[Parallel(n_jobs=8)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=8)]: Done  34 tasks      | elapsed:    9.2s
[Parallel(n_jobs=8)]: Done 184 tasks      | elapsed:   42.1s
[Parallel(n_jobs=8)]: Done 288 out of 288 | elapsed:  1.1min finished                                    2020-04-17 11:34 - nlsam - INFO - Now performing stabilization
[Parallel(n_jobs=8)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=8)]: Done  34 tasks      | elapsed:  1.3min
[Parallel(n_jobs=8)]: Done 145 out of 145 | elapsed: 10.7min finished
2020-04-17 11:46 - nlsam - INFO - Now denoising
2020-04-17 11:46 - nlsam - INFO - Found 18 b0s at position [  0  16  32  48  64  80  95 112 128 144 160 176 191 208 224 240 256 272]
2020-04-17 11:46 - nlsam - INFO - Now denoising volumes (240, 1, 105, 38, 30, 241) / block 1 out of 70.
[Parallel(n_jobs=8)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=8)]: Done  34 tasks      | elapsed:  4.6min
[Parallel(n_jobs=8)]: Done 143 out of 143 | elapsed: 42.6min finished
2020-04-17 12:29 - nlsam - INFO - Multiprocessing done in 42.58 mins.
2020-04-17 12:29 - nlsam - INFO - Now denoising volumes (272, 268, 2, 276, 29, 102) / block 2 out of 70.
[Parallel(n_jobs=8)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=8)]: Done  49 tasks      | elapsed: 12.3min
[Parallel(n_jobs=8)]: Done 143 out of 143 | elapsed: 41.2min finished
2020-04-17 13:10 - nlsam - INFO - Multiprocessing done in 41.15 mins.
2020-04-17 13:10 - nlsam - INFO - Now denoising volumes (144, 104, 186, 3, 36, 37) / block 3 out of 70.
[Parallel(n_jobs=8)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=8)]: Done  49 tasks      | elapsed: 12.7min
[Parallel(n_jobs=8)]: Done 143 out of 143 | elapsed: 41.9min finished
2020-04-17 13:52 - nlsam - INFO - Multiprocessing done in 41.85 mins.
2020-04-17 13:52 - nlsam - INFO - Now denoising volumes (176, 164, 4, 273, 142, 121) / block 4 out of 70.
[Parallel(n_jobs=8)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=8)]: Done  49 tasks      | elapsed: 12.8min
[Parallel(n_jobs=8)]: Done 143 out of 143 | elapsed: 41.6min finished
2020-04-17 14:34 - nlsam - INFO - Multiprocessing done in 41.56 mins.
2020-04-17 14:34 - nlsam - INFO - Now denoising volumes (191, 168, 99, 284, 5, 173) / block 5 out of 70.
[Parallel(n_jobs=8)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=8)]: Done  49 tasks      | elapsed: 13.5min
[Parallel(n_jobs=8)]: Done 143 out of 143 | elapsed: 43.0min finished
2020-04-17 15:17 - nlsam - INFO - Multiprocessing done in 42.95 mins.
2020-04-17 15:17 - nlsam - INFO - Now denoising volumes (64, 232, 129, 148, 214, 6) / block 6 out of 70.
[Parallel(n_jobs=8)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=8)]: Done  49 tasks      | elapsed: 12.2min
`

**Comment by samuelstjean** [comment]
It's a bit hard to read this way, but you cold also try to reduce the number of neighbors from 5 to say 3, that would reduce the size of the system of equations being solved at each step for example.

**Comment by rosella1234** [comment]
ok I will try. thank you

**Comment by rosella1234** [comment]
Hi, I would like to use the "auto" options both to N and sigma for denoising my data from HCP. The nlsam_denoising script still takes a lot of time on my PC. Could I please send you by email an example subject and see if the problem for this time requirement is my image? 
thank you,
Rosella

**Comment by samuelstjean** [comment]
I guess, you can try sending me just the id maybe I have a few hcp datasets on hand already

**Comment by rosella1234** [comment]
I should apply nlsam_denoising to a subset of 3T and 7T HCP subjects. An example ID is 100610. THank you very much

**Comment by rosella1234** [comment]
Here you find attached a link for an example subject folder. With the _auto_ options on, my laptop takes like 40 hours per subject, with N=1 and piesno as default option it takes like 8 hour per subject. I would like to use the auto option in order to estimate noise without an a-priori model, in and adaptive way. However, I can't understand whether it is normal it takes so long or not. **https://drive.google.com/open?id=1g16NvZQTilXiIEC703XT4nM2P64YqqxJ**
thank you

**Comment by rosella1234** [comment]
Hi . Any news with long computational time when applying noise estimation method "auto" when using HCP data?
thank you

**Comment by samuelstjean** [comment]
I'm a bit busy this week, but I'll try to get back to you.
